$('#sandbox-container .input-group.date').datepicker({
        format: "dd-mm-yyyy",
        startDate: 2016,
        endDate: 2020,
        startView: 1,
        minViewMode: 1,
        todayBtn: "linked",
        clearBtn: true,
        language: "fr",
        multidate: false,
        daysOfWeekDisabled: "0,1",
        daysOfWeekHighlighted: "3,4",
        calendarWeeks: true});